export const getAppElements = (doc = document) => ({
  input: doc.getElementById('questInput'),
  playerInput: doc.getElementById('playerInput'),
  playerLookupButton: doc.getElementById('playerLookup'),
  seriesFilter: doc.getElementById('seriesFilter'),
  toggleButton: doc.getElementById('toggleAll'),
  searchToggleButton: doc.getElementById('searchToggle'),
  backButton: doc.getElementById('backButton'),
  stepsDiv: doc.getElementById('steps'),
  titleDiv: doc.getElementById('questTitle'),
  overviewDiv: doc.getElementById('questOverview'),
  viewStepsToggle: doc.getElementById('viewStepsToggle'),
  viewModeToggle: doc.getElementById('viewModeToggle'),
  hideCompletedCheckbox: doc.getElementById('hideCompleted'),
  resultsDiv: doc.getElementById('searchResults'),
  progressIndicator: doc.getElementById('progressIndicator'),
  progressRow: doc.getElementById('progressRow'),
  wikiLink: doc.getElementById('wikiLink'),
  prevStepButton: doc.getElementById('prevStep'),
  nextStepButton: doc.getElementById('nextStep'),
  resetQuestButton: doc.getElementById('resetQuest'),
  jumpCurrentButton: doc.getElementById('jumpCurrent'),
  headerEl: doc.querySelector('header'),
  navBar: doc.querySelector('.nav-bar'),
  toggleBar: doc.querySelector('.toggle-bar'),
  stickyBar: doc.getElementById('stickyBar'),
  scrollTopButton: doc.getElementById('scrollTopButton'),
});
