export const state = {
  showAllSteps: false,
  sequentialStepChecking: true,
  currentItems: [],
  pendingAutoScroll: false,
  focusedStepIndex: null,
  currentQuestKey: null,
  currentRewardImage: null,
  currentOverview: null,
  currentKartographerLiveData: null,
  overviewChecks: {},
  showSteps: false,
  searchQuery: '',
  selectedSeries: 'alphabetical',
  playerName: '',
  playerQuestFilter: null,
  playerQuestMeta: {},
  playerSkills: {},
  playerLastFetchAt: null,
  searchState: {
    visibleResults: 0,
    reset: false,
    lastRenderedSeries: null,
  },
};
